bin/dockerfile_lint
=> Proper exit code when there is no error

bin/dockerfile_lint
Quick and dirty addition. Could use a bit of refactoring & error checking, but is functioning.
=> enable basic http & https checking

config/base_rules.yaml, index.js, sample_rules/basic_rules.yaml, sample_rules/label_rules.yaml, test/dockerfiles/TestLabels
Merging into temporary branch to allow folks to play with new label rule enhancements and provide feedback.
=> Prototype enhanced label rule handling

index.js, sample_rules/label_rules.yaml, test/dockerfiles/TestLabels
Fixed issue where only the first label  with a rule violation was being detected.
Also report error at the level specified in the rule.
=> Fix multi error bug for labels

README.md, bin/dockerfile_lint, sample_rules/basic_rules.yaml, test/integration/exec.spec.js
@aweiteka  - merge if this is enough to support your permissive flag request
fixes #24
=> Add strict mode

sample_rules/basic_rules.yaml, sample_rules/recommended_label_rules.yaml
Content merged for basic_rules and recommend_label_rules.
Creating PR for implementation now.
=> Content merged for basic_rules and recommend_label_rules.

bin/dockerfile_lint, lib/rulefile-loader.js, test/integration/exec.spec.js
=> Add --export-rule to dump effective rules for debugging

sample_rules/basic_rules.yaml
Add yum update all checks and privileged container runs
=> Add yum update all checks and privileged container runs

lib/parser.js
Closed the ? query string line separation.
Also, i forgot to close #43 after fixing the regex.
=> This closes #46 and closes #43

lib/linter-utils.js
=> Fix issue #50

config/default_rules.yaml
Resolves regex port number in FROM line
=> fixes 57 add support for port number in FROM line

lib/linter.js, lib/parser.js
=> Fix typo and error handling

config/default_rules.yaml, sample_rules/basic_rules.yaml, sample_rules/basic_rules_atomic.yaml, sample_rules/openshift.yaml, sample_rules/osbs.yaml
Fixes what I saw in #77 -- the rules array is formatted wrong.
=> fixing FROM rules array

.travis.yml, README.md, bin/dockerfile_lint, bin/functions.js, package.json, test/integration/exec.spec.js
Usage example:
```
node ./bin/dockerfile_lint -f Dockerfile -f Dockerfile2
```
=> Allow to pass several Dockerfiles with -f : close #86

config/default_rules.yaml, sample_rules/basic_rules.yaml, sample_rules/basic_rules_atomic.yaml, sample_rules/modules.yaml, test/data/rules/basic.yaml
Ref:
- https://github.com/moby/moby/commit/b5579a4ce33af4c1f67118e11b5a01008a36d26a
=> Update link of Docker deprecated.md file

bin/dockerfile_lint, test/integration/exec.spec.js
\+ printing valid JSON in case of multiple files
=> --json mode fixups: not printing "# Analyzing ..." message - fix #97

README.md
This will make the doc more readable :)
=> Fix and update README.md few code block syntax

README.md
Remove useless trailing spaces for documentation future maintainability
=> Remove README.md trailing spaces

README.md
Add Table of Contents to improve readability :)
=> Add "Table of Contents" to README.md

README.md
With this change, the command can be run without modification in [fish](https://fishshell.com/).
=> Use environment variable instead of subshell

config/default_rules.yaml, sample_rules/basic_rules_atomic.yaml, sample_rules/default_rules.yaml, sample_rules/modules.yaml, sample_rules/openshift.yaml, sample_rules/osbs.yaml
I have tested this regex with https://regex101.com/tests
It passes for: 
```
FROM nginx
FROM nginx:latest
FROM nginx:latest as foobar
```
=> Add support for "FROM image as name"
